### ISSUE TITLE
Show task hierarchy 

### ISSUE THREAD

**Issue by epernst** [tfenster/azdevops-vscode-simplify#11]
In our setup we always tag both the task# and the parent pbi/bug#, but the work item list in VSC only show the tasks.

So, it would be great if the work item list would show both the tag, and its parent and allow us to select both.

**Comment by tfenster** [comment]
You can configure the extension to also show your PBIs and bugs (see extension settings). And we can also look into supporting multi-select for the link, so you could select both the PBI/bug and the task when creating the branch. But that would be a bigger change, so I'd see it as more of a long-term enhancement. 

For the title of the issue: The task hierarchy is tricky as it is dynamic and can be completely different between organizations, projects and even individual work items. Therefore, it would also be more work which I don't expect to happen soon, if at all.

Of course, always feel free to create a PR!

**Comment by DavidFeldhoff** [comment]
Just to get it right: Would it be enough to display the work item id of the parent of a task (and being able to select both)?

**Comment by DavidFeldhoff** [comment]
@epernst We've solved it now like this in v0.0.7 (not shipped yet):
https://user-images.githubusercontent.com/53570297/205514181-b8a6fce9-4594-4e4d-9bce-7f47c32833ee.mp4

Hope that is going to match your requirements.
