### ISSUE TITLE
Work item type setting should also be supported in the tree

### ISSUE THREAD

**Issue by tfenster** [tfenster/azdevops-vscode-simplify#13]
@DavidFeldhoff not sure if I am missing anything, but I think because of https://github.com/tfenster/azdevops-vscode-simplify/blob/main/src/api/azdevops-api.ts#L304, the setting where we configure the relevant work item types is ignored in the tree, right?

**Comment by DavidFeldhoff** [comment]
Yes, **you** aren't missing anything, but it seems **I** was missing this line as I introduced that setting 😇

**Comment by DavidFeldhoff** [comment]
This is fixed now. Do you want to test it once yourself or should I close this, @tfenster ?

**Comment by tfenster** [comment]
Feel free to close :)
