### ISSUE TITLE
Expand project that corresponds to the currently opened git repo

### ISSUE THREAD

**Issue by DavidFeldhoff** [tfenster/azdevops-vscode-simplify#2]

**Comment by TKapitan** [comment]
This is something we would definitely appreciate! If you have more projects/organizations (in my case over 150 projects across 7 organizations) it's could be harder to find sometimes to right one.

Maybe (not sure if it's possible with the API) could be useful to have a view "organization>queries(eg. "Followed by me">projects (only projects that have some witem)".

**Comment by fvet** [comment]
> Maybe (not sure if it's possible with the API) could be useful to have a view "organization>queries(eg. "Followed by me">projects (only projects that have some witem)".

I agree on the above. In my case we've also 100+ projects of which 95% are not applicable to me. My current starting point is always the devops organisation (not the project page) which shows all of the **work items** that are assigned to my (spanning multiple projects). I normally have max. 20 non-closed work items assigned to me, so this list is quite easy to check. Having the a similar list of work items in _simplify_ would be great. (Avoiding the need to traverse the 'projects' structure) 

![image](https://user-images.githubusercontent.com/25268332/202920605-35d2a1fc-c6fc-4a30-a63c-f6bcb4aae7af.png)

**Comment by DavidFeldhoff** [comment]
I have a prototype locally already, but would like to check other ways as well.
Just asking: what would you think of this approach?
https://twitter.com/C4p0ne_/status/1594036265678094336?t=REKW4qAk2ONsvSGpnq5o3Q&s=19

Unfortunately that would come with quite an initial performance decrease which is why it's not our preferred solution, but if you would choose it, we might can make that possible. Until now I did not find an API that gets all the work items across projects in a fast way, but if there is any, then that would probably be the way. Any help appreciated.

Of course we can also try to have a look at other ways, but finding a fast api is probably the fastest solution

**Comment by tfenster** [comment]
The WIQL API that we use can actually be used without a project. Of course, "recent project activity" doesn't make sense in that context and isn't supported, but the other 4 queries should work and return results across projects in the same organization.

**Comment by DavidFeldhoff** [comment]
That sounds good! Didn't know that. Probably then this is already enough as we can find out which 5 % of the projects are needed and can directly get rid of all the other organizations and projects where we don't have work assigned or are not following any work, right? And then I would leave the current queries we have right now as they are as the 5% of the projects that are left are indeed relevant to me.

Is that a valid approach? Should we make that a setting to remove all projects and organizations which aren't relevant to us? Or should we do that always? What's your opinion on this @tfenster ?

**Comment by tfenster** [comment]
Please make it configurable. I can also imagine a workflow where a user doesn't have an assigned work item, but uses the tree to find a work item, open it in the browser and assign it to herself. That wouldn't work if we always hide them. Makes sense?

**Comment by DavidFeldhoff** [comment]
Hm.. I don't like to see the 95% of projects (I have the same case btw) that I will never use, because I might assign a work item to myself at some point in time. But I definitely also see your point. 

But maybe it's better then to
1. show all projects I have assigned work or: recent activity (hope that's doable)
2. in addition add a button to the view to load all if I'm still missing any projects (that scenario would mean that I want to search for a work item that I haven't work assigned to me and where I haven't been active for quite some time, so I think that's already a pretty rare edge case)
   ![image](https://user-images.githubusercontent.com/53570297/203405820-a9cd131f-b2b4-4622-b5b3-3355cffbfceb.png)

I think with that we have a clean view and also support the edge cases where I maybe assign first time a work item to myself in that project. Do you agree?

**Comment by tfenster** [comment]
Why not just have a setting? I'm ok with defaulting it to showing only projects with your work items. But if I want to see all (which happens to be the case for me), I don't want to open the extension and then having to click on that button. We could also have it as button as you suggest, but it should flip the setting, so that when I open VS Code the next time, it behaves as I left it last time.

Btw, how would it behave if you open a repo where you don't have assigned work items? For me, that is very realistic. Would it then still hide the project and consequently expand nothing?
