### ISSUE TITLE
What branch is new the branch based on when clicking "Create branch for this?"

### ISSUE THREAD

**Issue by guidorobben** [tfenster/azdevops-vscode-simplify#28]
Normally I create a new branch in devOps that is "based on" out dev branch. I noticed the "Create branch for this" is not creating a branch based on anything. When I create a branch, I do not get the new commits from other developers. Is there a way to make this functionality be based on another branch?

**Comment by DavidFeldhoff** [comment]
Currently the branch you're currently working on is the base-branch. So if you would start from your dev-branch, then the (local) dev-branch would be the base branch for your newly created one.

Can you please elaborate a bit more what you would expect? Do you want to have a possibility to always create a branch based on the default-branch of the remote without any further interaction? (e.g. on origin/develop)? Or do you always want to get a dropdown with all possible branches to select one of them?

**Comment by guidorobben** [comment]
I see you already made this? But I guess the most usable option is to use the following:  _Or do you always want to get a dropdown with all possible branches to select one of them?_

I checked VSC and I think the same functionality as "Git: Create branch from..."

**Comment by tfenster** [comment]
Yes, but VSC also has "Git: Create branch..." which basically does the same as we currently do

**Comment by fvet** [comment]
> I see you already made this? But I guess the most usable option is to use the following: _Or do you always want to get a dropdown with all possible branches to select one of them?_
> 
> I checked VSC and I think the same functionality as "Git: Create branch from..."

Should we always ask for the branch to base on? 

In our scenario, this would always be the remote default branch (e.g. origin/dev) So I would expect the simplify 'Create Branch' action to create a new branch based on the remote default branch.

**Comment by DavidFeldhoff** [comment]
@fvet VSCodes git extension cannot do that or am I missing something? I'm just thinking if we could reuse that setting as well.

But otherwise we might can do something like having two settings:
1. `createBranchBasedOn` with options `current` and `default branch of remote repo`
2. `askForBaseBranch` that's might be set via your toggle-idea. 

If the 2nd setting is activated, the 1st setting is just a proposal
If the 2nd setting is deactivated, we always create it based on the 1st setting.
