### ISSUE TITLE
[Feature Request] azdevops-vscode-simplify.createBranch.useFullWorkitemDescriptionInBranchName

### ISSUE THREAD

**Issue by fvet** [tfenster/azdevops-vscode-simplify#36]
Having used the '**Create Branch**' option in github, it would be nice if we could configure full branch name proposal for new branches created via AZDevOps Simplify.

We currently already have `azdevops-vscode-simplify.createBranch.useWorkitemIdInBranchName` which suggests the workitemid only, might be interesting to add a new setting to include the description (cleaned up from non-supported chars / capped to the max. allowed branch name). Some ideas:

- `useWorkitemDescriptionInBranchName` : suggest the work item description only (can be used in combination with `useWorkitemIdInBranchName`, if both are used, add a '-' in between)
- `useWorkitemIdDescriptionInBranchName`: : suggest the work item **id** and **description** 
- ...

![BranchName](https://user-images.githubusercontent.com/25268332/214270711-1a7b4da4-e971-41c8-af73-6843ad3717e4.gif)

**Comment by tfenster** [comment]
Hm, I don't like the idea of too many options, but it good be a selection instead of a bool maybe? Something like

`branchNameProposal`:
- nothing
- workitemId
- workitemDescription
- workitemIdAndDescription

Would that work for you?

**Comment by DavidFeldhoff** [comment]
The solution suggested by Tobias just made it to the main branch and will be released next time :)

**Comment by fvet** [comment]
Hi @DavidFeldhoff , seems like v0.0.8 has never been released, so "azdevops-vscode-simplify.createBranch.branchNameProposal" is not available yet ;)

**Comment by DavidFeldhoff** [comment]
You're totally right, sorry for that. Currently I'm unable to find as much time as I would like to have and I was hoping there could be more improvements/fixes in the next release which is why I did not start releasing it directly. Nevermind, the release was just started and you should see it in a minute showing up.

**Comment by DavidFeldhoff** [comment]
I'm going to close it first as I think it's finished, but please share your feedback how your testing went nevertheless. And if something is not as you expected, feel free to reopen.
