### ISSUE TITLE
No info if not sign in

### ISSUE THREAD

**Issue by TKapitan** [tfenster/azdevops-vscode-simplify#4]
Hi David,
There is no message or info if you are not signed in with an Azure Account. The menu shows the "loading" icon, but nothing else. 

PS: Maybe also add a few lines to the extension description that you need to be signed using the Azure Account extension.

**Comment by lvanvugt** [comment]
Something I wanted to report. TOok me some searching to u derstand that I needed to log into azure before getting view on my projects. So, fully agree with the above "PS".

**Comment by tfenster** [comment]
@TKapitan @lvanvugt it should look like this if you are not logged in:

![sign in](https://user-images.githubusercontent.com/15346084/202894890-7daef682-01d3-476b-b22d-15db0afc9e9e.gif)

But I guess this doesn't happen for you? I tried to improve the behavior with #5, let's see if David agrees with the approach

**Comment by DavidFeldhoff** [comment]
Would be nice to know if @TKapitan or @lvanvugt got that notification "You're not signed in". If that's not the case, but they did see that the devops-view was loading, then I think there's another thing going on that the current PR would not catch.

**Comment by lvanvugt** [comment]
Indeed did **not** get any notification.

**Comment by tfenster** [comment]
> Indeed did **not** get any notification. And now realize that I was checked in into another Azure environment (for COSMO Alpaca).

But then you should just see other organizations as it uses the same mechanism. Did you get the same error message as @TKapitan

**Comment by tfenster** [comment]
@TKapitan and @lvanvugt an you please try again with v0.0.3 of the extension which has just now been released?

**Comment by lvanvugt** [comment]
Getting error:

```
An unexpected error occurred while retrieving projects: AxiosError: Request failed with status code 401
```

I am currently logged in into with my personal (@live.nl) account, seeing this in the list first:
![image](https://user-images.githubusercontent.com/18466198/202981141-fd85734b-0659-491f-aa4a-30a5360c70b4.png)

Unfolding on the lower node getting:
![image](https://user-images.githubusercontent.com/18466198/202981223-65fef28e-be93-4ef6-8bd0-2288f38682d6.png)

When unfolding the upper node I got the error and no subnodes are displayed.

Yesterday I did get all my projects shwon as nodes.

**Comment by DavidFeldhoff** [comment]
bummer, so it's even worse now? @lvanvugt maybe we can have a look on that on sunday together?

**Comment by DavidFeldhoff** [comment]
@tfenster it's getting the memberId correctly and then tries to load the organization, but there it is failing
![image](https://user-images.githubusercontent.com/53570297/204134600-890b3362-947d-42de-bc25-6f5a0cf511b3.png)
Then Luc executed the https://app.vssps ... manually and got this as response:
![image](https://user-images.githubusercontent.com/53570297/204134665-5182a3cb-6ab2-465e-a803-1b1dd8f72610.png)
So it seems our solution is only working if the user has specific permissions to read the user - account mappings. I think we have to find another API that loads the organizations then.

**Comment by tfenster** [comment]
@DavidFeldhoff Is he by chance using a private Microsoft account or an email where both private and business accounts are linked? If I remember correctly, private accounts don't work and there are also known issues if you have an email where both are linked.

For "find another API": That actually was one of the biggest problems when creating COSMO Alpaca, and it took me days to figure out the currently implemented way. So if you find a new one, that would be highly appreciated, because the current implementation isn't great, but they only one I was able to find

**Comment by lvanvugt** [comment]
> @DavidFeldhoff Is he by chance using a private Microsoft account or an email where both private and business accounts are linked? If I remember correctly, private accounts don't work and there are also known issues if you have an email where both are linked.

With my private (MS) account lvanvugt@live.nl it all works well. With my 4PS work account it does not work. The latter is, however, linked to my private account to make use of my VS subscription. Might that be an issue?

**Comment by tfenster** [comment]
Very weird. But COSMO Alpaca works with your business account, right?

**Comment by lvanvugt** [comment]
Yes

**Comment by tfenster** [comment]
The next release of the extension will have an entry in the status bar that shows the currently connected user and tenant. Can you check what you see there when it becomes available?

**Comment by DavidFeldhoff** [comment]
short update: Luc and me are in contact and I sent him some insider-vsix with some deeper logging and a few experimental things. It seems we're getting closer to a solution.

**Comment by DavidFeldhoff** [comment]
Do we have any open issues here @TKapitan @lvanvugt ? There was an improvement sipped with an update (which is at least 2 months ago) and I haven't heared anything anymore, but not sure if it the improvement solved it entirely.

**Comment by tfenster** [comment]
No feedback for half a year, so I hope we can close this :)
