### ISSUE TITLE
Create branch : use git.branchPrefix

### ISSUE THREAD

**Issue by fvet** [tfenster/azdevops-vscode-simplify#7]
Our branching policy is to name branches with the developers prefix.

Therefore, we're using the "git.branchPrefix" setting in VS Code to propose a default branch prefix (e.g. **FVE/**) when creating a new branch via 'Git: create branch'. 

If we would create a branch from a work item in simplify, it would be nice if the proposed branch name (currently empty) would take info account the "git.branchPrefix" setting too.

More info: https://code.visualstudio.com/updates/v1_68#_git-branch-prefix

**Comment by tfenster** [comment]
@fvet This should be fixed now and will be available with the next release. If not, please re-open and let us know what is missing
