### ISSUE TITLE
Missing work item id if description is too long.

### ISSUE THREAD

**Issue by fvet** [tfenster/azdevops-vscode-simplify#8]
In all our developments, the work item **id** is the most important reference.
We also include the id in the **branch names**.

In the simplify list of work items, the work item id is however not visible if the work item description is **too long**.

If I would create a branch name for the first work item (cfr. screenshot), I don't see the work item id (without enlarging the entire pane).

![image](https://user-images.githubusercontent.com/25268332/202919975-fe208a6b-66d6-4a05-acc5-f9abc63e58e9.png)

For the second work item, the id is visible, while it's not for the first.

Possible solutions: 
- Include the id in the data shown when hovering the work item (does not solve above issue)
- Creating a label with 'Descri... #id' based on the width of the pane (not sure if this is possible to truncate the description)
- Put id in front of the description: **#id** description.
- (Preferred) Propose id in the suggested branch name. Our current branch naming policy is **DEVPREFIX/ID_DESC** (e.g. FVE/1234_MyWorkItemDescription). So with #7 we could have already FVE/1234 as proposed branch name. (Description can then be added manually to a short description of the work item)

**Comment by tfenster** [comment]
Also a good idea. I'll try to implement that with a feature toggle so everyone can decided to use it or not

(I personally would never use that structure as I already have linked my work item and the branch, so why repeat the random ID in the branch name. But of course, if you want, that should be doable)

**Comment by tfenster** [comment]
@fvet This should be fixed now and will be available with the next release. If not, please re-open and let us know what is missing

**Comment by fvet** [comment]
Thanks.

For my info, solve via a configuration setting `azdevops-vscode-simplify.useWorkitemIdInBranchName` to trigger the inclusion of the work item id in the proposed branch name
